


custom-items:
  flagPillar:
    material: STICK
    name: "§fСтолб для флага"
    lore:
      - "§fА вот и первый шаг к созданию флага!"
      - "§7Используется при создании"
      - "§7основы флага"
  flagBasic:
    material: STICK
    name: "§aОснова флага"
    lore:
      - "§fДолжен же на чем-то болтаться флаг..."
      - "§7Используется при создании"
      - "§7флага"
  flagCloth:
    material: FLOWER_BANNER_PATTERN
    name: "§aЦветная тряпка"
    lore:
      - "§fНеплохой узор!"
      - "§7Используется при создании"
      - "§7флага"
  flag:
    material: END_ROD
    name: "§9§lФлаг"
    lore:
      - "§fЧто ж... ответственный момент,"
      - "§fкоторый ознаменует начало"
      - "§fвеликих событий."
      - "§7Размещает столб и флаг высотой"
      - "§76 блоков и шириной 4 блока"